services:
  nginx:
    image: nginx:latest
    container_name: gateway
    depends_on:
      - lipidserver
    volumes:
      - ./docker-build/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs/nginx
    networks:
      - app-network
    # Development
#    ports:
#      - '8080:80'
    # Production
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HOST_SERVER_DOMAIN_NAME=lipidxte.mpi-cbg.de

  lipidserver:
    stdin_open: true
    image: "scicomp/lipid-server:nginx"
    container_name: lipidserver
    hostname: lipidserver
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "scicomp/lipid-server:nginx"
    restart: unless-stopped
    command: yarn dev
    networks:
      - app-network

    volumes:
      - ./docker-build/download:/app/download
      - ./docker-build/sample:/app/sample
      - ./web:/app/web

    develop:
      watch:
        - action: sync
          path: ./docker-build/lipidXte
          target: /app/lipidXte
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

networks:
  app-network:
    driver: bridge